# Generated by Django 5.1.2 on 2024-10-18 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0002_alter_student_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='password2',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
