# Generated by Django 5.1.2 on 2024-10-18 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0003_student_password1_student_password2'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='username',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
