# Generated by Django 5.1.2 on 2024-10-19 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_number', models.IntegerField(primary_key=True, serialize=False)),
                ('capacity', models.IntegerField()),
                ('occupied', models.BooleanField(default=False)),
            ],
        ),
    ]
