# Generated by Django 4.2.8 on 2024-10-23 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_announcements'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Announcements',
        ),
    ]
