# Generated by Django 5.1.2 on 2024-10-26 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0003_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='recived',
            field=models.BooleanField(default=False),
        ),
    ]
